org: yeimivarela
service: igp-sismos-scraper

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  # Default memory size for functions (default: 1024MB)
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::985026482300:role/LabRole

  environment:
    DYNAMO_TABLE_NAME: IGP_Sismos

functions:
  scrapIGPSismos:
    handler: igp_scraper.lambda_handler
    events:
      - http:
          path: igp/sismos
          method: get
          cors: true

resources:
  Resources:
    IGPSismosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: IGP_Sismos
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
